### ISSUE TITLE
Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by mjball** [phallstrom/AlfredGist#12]
I'd like to be able to use this extension for private GitHub installations.

**Comment by cralor** [comment]
Just for future Google-ers...

Your Enterprise Endpoint might need to be "gist configure server my.privategit.com/api/v3" or something similar to work.

Side affects of an issue like this will be login redirects, for example.
You can also use Alfred's workflow debugging tool for troubleshooting.

Enjoy!

**Comment by mjball** [comment]
I'm back, setting up a new machine for the first time in a while. Reminder to self and a note for future googlers: omit the `https://` from the server configuration, so it's just `{hostname}/api/v3`.
