### ISSUE TITLE
`gist` command is very slow with "large" amounts of text

### ISSUE THREAD

**Issue by mjball** [phallstrom/AlfredGist#17]

**Comment by Pash237** [comment]
Is there any workaround for this?
I use **gist** to send some logs or server responses which are too large to just send over Skype/Hangouts/Whatever.
And sending 30KB text from clipboard takes minutes on my MacBook Pro :(

![CPU usage](http://dl.dropbox.com/u/3400922/Screenshots/h~.png)

**Comment by Pash237** [comment]
This high CPU usage was because of gist content escaping done in bash with multiple regular expressions. I've fixed it by escaping using `json.dumps` from Python – now gist uploads are instant. Hope it didn't break anything.

**Comment by phallstrom** [comment]
Everyone - This is fixed via #27 and a new workflow is available here: https://github.com/phallstrom/AlfredGist/blob/master/Gist.alfredworkflow?raw=true
