### ISSUE TITLE
Config option to prevent opening gist in browser

### ISSUE THREAD

**Issue by iakshay** [phallstrom/AlfredGist#21]

**Comment by alvinnguyen** [comment]
+1

**Comment by phallstrom** [comment]
Chiming in way late, but this has been an option for awhile now. Type 'gistconfig' into alfred to adjust the setting.  New workflow here: https://github.com/phallstrom/AlfredGist/blob/master/Gist.alfredworkflow?raw=true

**Comment by Pash237** [comment]
I don't see the option in the current workflow :(
![](http://dl.dropbox.com/u/3400922/Screenshots/i3.png)
And the code to open the gist in the browser it unchanged:
![](http://dl.dropbox.com/u/3400922/Screenshots/i2.png)

**Comment by phallstrom** [comment]
Ugh. My bad. I can't read and thought you mean "copying the url to clipboard."  Reopening...

**Comment by phallstrom** [comment]
@iakshay This is now in place. Grab the new workflow and type `gistconfig` and you should see the option.  refs 50b4ae4

**Comment by iakshay** [comment]
@phallstrom Thats great! Will check it out this week.
