### ISSUE TITLE
Can't create gist from ipynb files

### ISSUE THREAD

**Issue by tdhopper** [phallstrom/AlfredGist#23]
Whenever I try to create a gist from an *.ipynb file, I get

```
ERROR: An API error occured.

{
  "message": "Validation Failed",
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist",
  "errors": [
    {
      "resource": "Gist",
      "code": "missing_field",
      "field": "files"
    }
  ]
}
```
 IPython Notebook files are just JSON. If I change the extension to `*.py`, it works fine.

**Comment by phallstrom** [comment]
I'm not sure how I never replied to this. My [super] bad. Can you grab the most recent workflow and let me know if this is still an issue.  I wonder if Github thinks it's a binary file or simply not on their allowed list so rejecting it.  Would it be reasonable to simply rename any .ipynb files to .py when you gist them?

**Comment by phallstrom** [comment]
Open this back up if needed.
