### ISSUE TITLE
ERROR: An API error occurred

### ISSUE THREAD

**Issue by walterdolce** [phallstrom/AlfredGist#25]
Hi,
I've installed AlfredGist by following the instruction in the README file. I've created and successfully set the token but whenever I try to do anything with this extension I get the error "ERROR: An API error occurred".

FYI - I don't have any Alfred Gist or something like that in the authorized applications on GitHub. The extension didn't ask anything like that (and in case is required, it's not on the README).

**Comment by phallstrom** [comment]
Sorry for the long delay.  So you have the personal access token created in github and 'gist' is the only thing that's checked right?  I just went through the steps (turns out I don't have my own workflow installed :) and it's working for me right now.

Any chance it didn't get copied in correctly?  Verify that when you type 'gistconfig' the information is there correctly and that the API server is 'api.github.com'.

**Comment by walterdolce** [comment]
Yep. Everything seems to be set correctly. I will double check again though and confirm whether it works or not.

Also if you knew a way I could debug this would be great.

**Comment by phallstrom** [comment]
@walterdolce If you open a terminal and cd into the workflow's directory (or just download this repo and use that), then copy something innocent to the clipboard you can then run `sh -x gist.sh gist` which will display a ton of output.  Look for the lines with `curl` in them to see what the response is.  Or post it here, or send it to me privately as your token key will be in the output.

**Comment by walterdolce** [comment]
@phallstrom never mind. Apparently I was just being silly. I double checked the config params and it's working fine. Closing this issue. Thanks for the support :)

**Comment by gandalfsaxe** [comment]
@phallstrom I got the same error and suspected that the API server was incorrectly set. For me it was set to `https://github.com/phallstrom/AlfredGist` by default, which obviously can't be true.

Only by finding this issue did I find the correct server address: `api.github.com`. Shouldn't this be default?

But it works now 🙂

**Comment by phallstrom** [comment]
@GandalfSaxe It is the default. See https://github.com/phallstrom/AlfredGist/blob/master/functions.sh#L92

Any chance you had that URL copied and did gistconfig and selected one of the options unintentionally?

**Comment by gandalfsaxe** [comment]
Ah yes that's probably what happened 👍
