### ISSUE TITLE
Overwrite prefix directory.

### ISSUE THREAD

**Issue by blainesch** [phallstrom/AlfredGist#26]
I use Alfred on multiple computers and using Alfred's sync feature is pointing to a dropbox . All configuration right now is per-box. So setting up a new box has a manual step of configuring this plugin.

It would be great to be able to overwrite the prefix directory.

Currently this is hardcoded over here:
https://github.com/phallstrom/AlfredGist/blob/master/gist.sh#L3

This could be overwritten in the plugin itself and the `gist.sh` only sets it if not currently set.

**Comment by phallstrom** [comment]
@blainesch It's been awhile since I tracked Alfred workflow internals.  What do you mean by "overwritten in the plugin itself"?  I totally get why you want this, just not sure how to go about it. Any pointers to docs or other insights appreciated.

**Comment by blainesch** [comment]
In another plugin I have, I set a env variable in the bash command itself in the "Run Script" in the alfred workflow editor. So something like this:

~~~bash
bash gist.sh _files {query}
~~~

Would become:

~~~bash
PREF_DIR=/foo/bar/baz bash gist.sh _files {query}
~~~

The plugin would just not set the variable if it's already set.

**Comment by phallstrom** [comment]
Ah! Hadn't thought about that. That's a nice way to do it. So you'd just tweak that on your machines and let it go.  Seems like something I could do.  Stay tuned.

**Comment by phallstrom** [comment]
@blainesch Have a new workflow for you to try out. Think I found a better way than having to adjust the workflow scripts themselves.  Give this a try and let me know if it works for you.

- Install new workflow.
- Create a directory in your dropbox and copy the full path to it (ie. /Users/blaine/Dropbox/alfred-gist-config)
- Open Alfred and type `gistconfig`.
- Select the new "shared config directory" option so it picks up your new directory.

- Make sure you can still gist.
- You should also see a `config` file in that shared directory that has your new settings.

On a new machine do the same as the above and it should pick up your shared settings.

Let me know what happens.

**Comment by phallstrom** [comment]
This is now part of the latest workflow available here: https://github.com/phallstrom/AlfredGist/blob/master/Gist.alfredworkflow?raw=true
