### ISSUE TITLE
Tolerant to more file format?

### ISSUE THREAD

**Issue by homever** [phallstrom/AlfredGist#28]
Trying to upload some `.conf` file, upon selection, the workflow returns a notification saying "An API Error occurs... message,..validation failed.."

**Comment by phallstrom** [comment]
Any chance you can share that `.conf` file with me so I can try to reproduce it?

**Comment by homever** [comment]
Of course. A case is here:
https://gist.github.com/homever/d20c1dd3ac802039c98c

One more question, is it doable to update existing gist from the workflow?

**Comment by phallstrom** [comment]
Thanks. Not possible to update via workflow.

To clarify - this broke when using the clipboard or file selection or both?

**Comment by homever** [comment]
Sorry for the late reply.
It only happens when doing file selection.

**Comment by phallstrom** [comment]
Ugh, I hate this, but that file works for me using file selection.  Result: https://gist.githubusercontent.com/phallstrom/c7b0df18793d44316a968648bdb4b79b/raw/4eed076d0fff4f560a63252ce0be8482ac198c7e/surge_main.conf

Any chance it changed from what you original uploaded?

**Comment by homever** [comment]
That is so strange and now it works like a charm. I was not able to execute upon file selection in Alfred 2, but now I've upgraded to version 3 and the latest OS X, so I was not able to find the possible reasons...
Thanks!
