### ISSUE TITLE
upload screen captures

### ISSUE THREAD

**Issue by anaderi** [phallstrom/AlfredGist#29]
wouldn't it be nice to upload screen captures as well?

**Comment by phallstrom** [comment]
Gist supports images? Can you point me to that feature? I'm not seeing it.

**Comment by anaderi** [comment]
for example 
https://gist.github.com/anaderi/f46b56e40c4f91ecbd7d

**Comment by phallstrom** [comment]
@anaderi Doesn't look like this is very feasible. Best I can tell to add images to gists you have to "git clone" the gist and then operate it on it like a normal git repo.  It could be done, but I'm not sure I'll get around to it :/
