### ISSUE TITLE
Submit Workflow to packal.org to enable auto updates 

### ISSUE THREAD

**Issue by digiltd** [phallstrom/AlfredGist#30]
Hi, I use this Workflow quite a bit so thanks for making it.

I noticed that it was still writing to `Library/Application Support/Alfred 2/Workflow Data/` even though I am using Alfred 3.

This was because I was using an old version. Any chance you can submit the Workflow to packal.org so updates can be pushed to the user?

Thanks

**Comment by digiltd** [comment]
oops, not it hasn't been fixed so ignore for now

**Comment by phallstrom** [comment]
What hasn't been fixed?  I'll admit I wrote this before packal.org was around/viable/worked/etc... so.. happy to make tweaks, but not sure what you mean :)

**Comment by digiltd** [comment]
I thought the `$PREF_DIR` was no longer hard coded but it appears it still is. Not that it causes problems, but when using Alfred 3 it creates a folder in the wrong place.

You can set environment variables fairly easily in Alfred 3.

http://www.alfredforum.com/topic/9070-how-to-workflowenvironment-variables/

I was going to have a tweak of your version to convert it over, but happy to let you tweak away :)

**Comment by phallstrom** [comment]
Happy to take a pull request!
