### ISSUE TITLE
Does not work on Alfred V3.x.x (?)

### ISSUE THREAD

**Issue by ibrowne** [phallstrom/AlfredGist#31]
Trying to use this on Alfred 3.2.1 and every time I go to create Gist from clipboard, it tells me I need to configure gist via 'gist help'.  I do this and it brings me here.  Is there something else I can try?

**Comment by phallstrom** [comment]
Did you follow the steps here? https://github.com/phallstrom/AlfredGist#setup

**Comment by ibrowne** [comment]
I did that a while ago, and just earlier today when doing 'gistconfig', setting the api token was not an option for some reason.  I re-generated my already existing GitHub api token and was then able to enter that into the alfred GIST workflow as described via your link.  It seems to be working now. Thanks.
