### ISSUE TITLE
Clipboard replaced with "{"

### ISSUE THREAD

**Issue by mattburman** [phallstrom/AlfredGist#32]
The Gist is posted,
Clipboard copying notification is delivered
the URL copied is always '{'

**Comment by mattburman** [comment]
Seems like `get_json_key` always returns `{`
Also tried getting `url` rather than `html_url` and got the same

**Comment by phallstrom** [comment]
@mattburman (sorry so late) I just tried it and it is working for me. Do you have any special configs and/or are posting to somewhere other than github.com? Would you be willing to tweak the script to echo `key` and `json` to a temp file and share it here? Only thing I can think is that you're seeing something else than I am.
